config/routes.rb
Blogyr::Application.routes.draw do
  match '/admin', :to => 'admin/posts#index', :as => 'admin'

  namespace :admin do
    resources :posts
    resources :categories
  end

  get "session/login"
  get "contacts/index"
  get "contacts/send"

  match "/p/c", :to => "posts#comment", :as => "post_comment"
  match "/p", :to => "posts#index"
  match "/p/:id", :to => "posts#show", :as => "post"

  match "/c/:id", :to => "posts#by_cat", :as => "category"

  devise_for :users, :controllers => { :sessions => "sessions" }
  devise_scope :user do
    match "/users/ulogin", :to => "sessions#ulogin"
    match "/users/setName", :to => "sessions#updateName"
  end

  root :to => "posts#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
  attr_accessible :name

  validates_presence_of :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :author, :class_name => "User"
  belongs_to :post

  attr_accessible :body, :post_id

  validates_presence_of :body, :author
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :friendly_url, :show, :title, :categories, :category_ids

  validates_presence_of :body, :title

  has_and_belongs_to_many :categories
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :uid

  has_many :comments

  validates_uniqueness_of :name
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find params[:id]
  end

  def create
    @category = Category.new params[:category]

    if @category.save
      redirect_to admin_categories_path
    else
      render :action => 'new'
    end
  end

  def update
    @category = Category.find params[:id]

    if @category.update_attributes params[:category]
      redirect_to admin_categories_path
    else
      render :action => 'edit'
    end

  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id params[:id]
  end

  def edit
    @post = Post.find_by_id params[:id]
    @categories = Category.all
  end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    @post = Post.new params[:post]

    if @post.save
      redirect_to [:admin, @post], :notice => "Post was created"
    else
      render :action_new
    end
  end

  def update
    @post = Post.find params[:id]

    if @post.update_attributes params[:post]
      redirect_to [:admin, @post], :notice => "Post was updated"
    else
      render :action => "edit"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end

  def send_feedback
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  helper_method :current_user

  def index
    @posts = Post.paginate :page => params[:page]
    @categories = Category.all
  end

  def show
    @post = Post.find params[:id]
    @comment = Comment.new
    @comment.post = @post
  end

  def by_cat
    @category = Category.find params[:id]
    @posts = @category.posts

    @categories = Category.all
    render :index
  end

  def comment
    @comment = Comment.new
    @comment.body = Sanitize.clean(params[:comment][:body], Sanitize::Config::BASIC)
    @comment.post = Post.find params[:comment][:post_id]
    @comment.author = current_user

    if @comment.save
      redirect_to @comment.post
    else
      render :action => "show"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def ulogin
    require 'net/http'

    url = URI.parse("http://ulogin.ru/token.php?token=#{params[:token]}")

    social_info = ActiveSupport::JSON.decode(Net::HTTP.get(url))

    user = User.where("email = :email or uid = :uid", { :email => social_info["email"].downcase, :uid => social_info["uid"].downcase}).first

    if user.nil?
      user = User.new
      user.email = social_info["email"].downcase
      user.uid = social_info["uid"].downcase
      user.name = social_info["nickname"]
      user.password = params[:token]
      user.save!
      sign_in user, :bypass => true
    else
      sign_in user, :bypass => true
    end

    render json: {:status => "Ok", :userName => user.name }
  end

  def updateName
    user = current_user
    user.name = params[:name]
    if user.save
      render json: {:status => "Ok"}
    else
      user.reload
      render json: {:status => "Error", :userName => user.name}
    end
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/categories/_form.html.haml
= form_for [:admin, @category], :html => { :class => "form-horizontal" } do |f|
  %div#errors
    - @category.errors.full_messages.each do |msg|
      %h3
        = msg
  = field_set_tag "Category" do
    %div.control-group
      = f.label :name, :class => "control-label" #'topic', nil, :class => "control-label"
      %div.controls
        = f.text_field :name
    %div.control-group
      = submit_tag "Save"

app/views/admin/categories/edit.html.haml
- content_for :admin_header do
  %div#links.pull-right{:style => "margin: 10px auto;"}
    %a.btn{:href => admin_categories_path}
      Back
= render 'form'

app/views/admin/categories/index.html.haml
- content_for :admin_header do
  %h2.pull-left
    Categories
  %div#links.pull-right{:style => "margin: 10px auto;"}
    %a.btn{:href => new_admin_category_path}
      New

%table.table.table-stripped
  %thead
    %tr
      %th{:style => "width: 40%;"}
        Title
      %th{:style => "width: 40%;"}
        Usage
      %th{:style => "width: 20%;"}
        Actions
  %tbody
  - @categories.each do |category|
    %tr
      %td
        = category.name
      %td
        = category.posts.count
      %td
        %a.btn{:href => edit_admin_category_path(category)}
          %i.icon-edit
        %a.btn{:href => "#"}
          %i.icon-remove

app/views/admin/categories/new.html.haml
- content_for :admin_header do
  %div#links.pull-right{:style => "margin: 10px auto;"}
    %a.btn{:href => admin_categories_path}
      Back
= render 'form'

app/views/admin/posts/_form.html.haml
= form_for [:admin, @post], :html => { :class => "form-horizontal" } do |f|
  %div#errors
    - @post.errors.full_messages.each do |msg|
      %h3
        = msg
  = field_set_tag "Post" do
    %div.control-group
      = f.label :title, :class => "control-label" #'topic', nil, :class => "control-label"
      %div.controls
        = f.text_field :title
    %div.control-group
      = f.label :friendly_url, :class => "control-label"
      %div.controls
        = f.text_field :friendly_url
    %div.control-group
      = f.label :body, :class => "control-label"
      %div.controls
        = f.cktext_area :body
    %div.control-group
      = f.label :categories, :class => "control-label"
      %div.controls
        = f.hidden_field :category_ids, :name => "post[category_ids][]"
        %ul#categories
          - @categories.each do |category|
            %li.variant{"data-cat" => category.id}
              = category.name
    %div.control-group
      %div.controls
        %label.checkbox
          = f.check_box :show
          Public
        = submit_tag "Save"

app/views/admin/posts/edit.html.haml
= render 'form'

app/views/admin/posts/index.html.haml
- content_for :admin_header do
  %h2.pull-left
    Posts
  %div#links.pull-right{:style => "margin: 10px auto;"}
    %a.btn{:href => new_admin_post_path}
      New

%table.table.table-stripped
  %thead
    %tr
      %th{:style => "width: 40%;"}
        Title
      %th{:style => "width: 40%;"}
        User-friendly URL
      %th{:style => "width: 20%;"}
        Actions
  %tbody
  - @posts.each do |post|
    %tr
      %td
        = post.title
      %td
        = post.friendly_url
      %td
        %a.btn{:href => edit_admin_post_path(post)}
          %i.icon-edit
        %a.btn{:href => "#"}
          %i.icon-remove

app/views/admin/posts/new.html.haml
- content_for :admin_header do
  %div#links.pull-right{:style => "margin: 10px auto;"}
    %a.btn{:href => admin_posts_path}
      Back
= render 'form'

app/views/admin/posts/show.html.haml
- content_for :admin_header do
  %div#links.pull-right{:style => "margin: 10px auto;"}
    %a.btn{:href => edit_admin_post_path(@post)}
      Edit
    %a.btn{:href => admin_posts_path}
      Back


%p#notice
  = notice
%p
  %b
    Title
  = @post.title

%p
  %b
    Friendly URL
  = @post.friendly_url

%p
  %b
    Body
  %hr
  = raw @post.body
  %hr

app/views/contacts/index.html.haml
%h2
  = t(:contact_me)

app/views/contacts/sendfeedback.html.haml
%h1 Contacts#send
%p Find me in app/views/contacts/sendfeedback.html.haml

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Blogyr - Admin
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "admin"
    = csrf_meta_tags
  %body
    %div.container
      %div#header
        %ul.nav.nav-pills.pull-right
          %li
            %a{:href => root_path}
              = t(:home)
          %li
            %a{:href => admin_posts_path}
              = t(:posts)
          %li
            %a{:href => admin_categories_path}
              = t(:categories)
        %h3.muted
          Blogyr - Admin
      %div#subHeaderWrapper.row-fluid
        %div#admin_header.span12
          = yield :admin_header
      %div#contentWrapper.row-fluid
        = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blogyr
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "//ulogin.ru/js/ulogin.js"
    = csrf_meta_tags
  %body
    %div.container
      %div#header
        %ul.nav.nav-pills.pull-right
          %li{:class => ("active" if controller.controller_name == "posts")}
            %a{:href => root_path}
              = t(:home)
          %li{:class => ("active" if controller.controller_name == "contacts")}
            %a{:href => contacts_index_path}
              = t(:contact_me)
          -if current_user.try(:admin?)
            %li
              %a{:href => admin_path  }
                = t(:admin)
          - if user_signed_in?
            %li{:class => ("active" if controller.controller_name == "session")}
              %a{:href => destroy_user_session_path}
                = t(:sign_out)
        %h2.muted
          Blogyr
      %div#contentWrapper.row-fluid
        %div#content.span10
          = yield
        - if content_for?(:sidebar)
          %div#sidebar.span2
            = yield(:sidebar)

app/views/layouts/devise.html.haml
!!!
%html
%head
%title Blogyr
= stylesheet_link_tag    "application", :media => "all"
= javascript_include_tag "application"
= csrf_meta_tags
%body
  %div.container
    %div#header
      %ul.nav.nav-pills.pull-right
        %li{:class => ("active" if controller.controller_name == "posts")}
          %a{:href => root_path}
            Home
        - if user_signed_in?
          %li{:class => ("active" if ["sessions", "passwords", "registrations"].include? controller.controller_name)}
            %a{:href => destroy_user_session_path}
              Sign out
        - else
          %li{:class => ("active" if ["sessions", "passwords", "registrations"].include? controller.controller_name)}
            %a{:href => user_session_path}
              Sign in
        %li{:class => ("active" if controller.controller_name == "contacts")}
          %a{:href => contacts_index_path}
            Contact Me

      %h3.muted
        Blogyr
    %div
      = yield

app/views/posts/_comment.html.haml
= form_for @comment, :url => post_comment_path do |f|
  %legend
    = t(:post_comment)
  = f.cktext_area :body
  = f.hidden_field :post_id
  %br
  %div{:style => "margin-right: 400px;"}
    = f.submit :value => t(:post_comment), :class => "btn"
%div.user-settings
  %div.input-append
    %label{:style => "display: inline-block; margin: 5px;"}
      = t(:comment_as)
    %input.input-medium#userName{:type => "text", :disabled => '', :value => (current_user.name if current_user)}
    %button.btn#changeName{:type => "button"}
      %i.icon-cog#changeNameIcon

app/views/posts/index.html.haml
- @posts.each do |post|
  %div.post{:style => "margin-bottom: 20px;"}
    %h2
      %a{:href => post_path(post)}
        = post.title
    %p.muted
      %small
        = l post.created_at
    - c = post.body.match /(.*)<!--more-->(.*)/m
    - if c.nil?
      = raw post.body
    - else
      = raw c[1]
      %p
        - post.categories.each do |cat|
          %small.muted
            = cat.name
        %span.pull-right
          %a{:href => post_path(post)}
            = t(:read_more)
    %hr
%div.pagination-centered
  = will_paginate @posts, :renderer => BootStrapLinkRenderer

- content_for(:sidebar) do
  %div
    %h4.muted
      = t(:categories)
    %hr{:style => "margin: 5px 0px;"}
    %ul.categories
      - @categories.each do |cat|
        %li
          %a{:href => category_path(cat)}
            = cat.name

app/views/posts/show.html.haml
%h2
  = @post.title
- c = @post.body.match /(.*)<!--more-->(.*)/m
- if c.nil?
  = raw @post.body
- else
  = raw c[1]
  = raw c[2]
%hr
%div#comments
  - if @post.comments.none?
    %p{:style => "text-align: center;"}
      %strong
        = t(:no_comments)
  - else
    - @post.comments.each do |comment|
      %div.comment-container
        %p
          %span.text-info
            %strong
              = comment.author.name
          %span.muted
            %small
              = l comment.created_at
        %div.comment{:style => "border-bottom: 1px solid #eeeeee; padding-bottom: 10px;"}
          = raw comment.body
%div.comment-editor-container
  %div#notification
    %h3#notification_message
      This name is not available
  - if not user_signed_in?
    %div.comment-tab#warning
      %div{}
        %p{:style => "text-align: center;"}
          = t(:sign_in_to_comment)
        %div#uLogin{"data-ulogin" => "display=panel;fields=first_name,last_name,email,nickname;providers=google,facebook,twitter,vkontakte,linkedin;hidden=yandex,livejournal,openid,lastfm,liveid,soundcloud,steam,flickr,vimeo,youtube,webmoney;redirect_uri=;callback=uLoginAuth", :style => "margin: 0 auto; width: 252px;"}
    %div.comment-tab.comment-hidden#editor
      = render "comment"
    %div.comment-tab.comment-hidden
  - else
    %div.comment-tab
      = render "comment"